#!/usr/bin/env ruby
require "rubygems"
require File.dirname(__FILE__) + '/../app/models/basic_user'
require "termios"

def usage
	STDERR.puts <<USAGE
script/basic_user crypt|add …
	script/basic_user crypt		— print the appropriate hash for the entered password
	script/basic_user add USERNAME	— print a username:hash line, suitable for appending onto the auth.passwd file
	anything else will print this message
USAGE
	exit 1
end

def read_password
	def echo(flag)
		term = Termios::getattr(STDIN)
		if flag
			term.c_lflag |= Termios::ECHO
		else
			term.c_lflag &= ~Termios::ECHO
		end
		Termios::setattr(STDIN, Termios::TCSANOW, term)
	end
	
	begin
		STDERR.puts "Password:"
		echo(false)
		STDIN.gets.chomp
	ensure
		echo(true)
	end
end

case ARGV[0]
when "crypt"
	ARGV.size == 1 or usage
	puts BasicUser.crypt(read_password)
when "add"
	ARGV.size == 2 or usage
	user = BasicUser.new(:username => ARGV[1], :password => read_password)
	puts "#{user.username}:#{user.password_hash}"
else
	usage
end
